version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8081:8080
    environment:
     -  MONGODBATLAS_CLUSTER_CONNECTIONSTRING=mongodb+srv://timotiusgiovandi:89i09BcdjTWUaBsU@cluster0.mqtw9jg.mongodb.net
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    environment:
      - VITE_API_URL=https://backend:8081
