version: '0.1'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  webapi:
    image: my-dotnet-api
    container_name: webapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      MONGO_CONNECTION_STRING: "mongodb://root:example@mongodb:27017"
    ports:
      - "8080:8080"
  
  cdpfrontend:
    image: img-cdp-frontend
    container_name: ctr-cdp-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # environment:
    #   VITE_API_URL: "http://localhost:8080"
    depends_on:
      - webapi
    ports:
      - "3000:80"
