version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8081:8080
  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=https://backend:8081
