---
- name: Deploy Customer Data Platform
  hosts: web_servers
  become: true
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
    
    - name: Install Docker & Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Clone Backend Repository (.NET)
      git:
        repo: "https://github.com/timgio26/customerDataPlatform_mongoDb.git"
        dest: "/home/ubuntu/backend"
        version: "main"

    - name: Clone Frontend Repository (React)
      git:
        repo: "https://github.com/timgio26/customerDataPlatform_react.git"
        dest: "/home/ubuntu/frontend"
        version: "main"

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Start Application with Docker Compose
      command:
        cmd: docker-compose up -d
        chdir: /home/ubuntu/
