- name: Deploy App
  hosts: servers
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Run Docker Compose
      command:
        cmd: docker-compose up -d
        chdir: /home/app/
